const CONSTANTS = {

  GET_DEAL: 'GET_DEAL',
  GET_DEAL_SUCCEED: 'GET_DEAL_SUCCEED',
  GET_DEAL_FAILD: 'GET_DEAL_FAILED',

  GET_TOP_CATEGORY: 'GET_TOP_CATEGORY',
  GET_TOP_CATEGORY_SUCCEED: 'GET_LIST_TOP_SUCCEED',
  GET_TOP_CATEGORY_FAILED: 'GET_TOP_CATEGORY_FAILED',

  GET_LIST_CATEGORY: 'GET_LIST_CATEGORY',
  GET_LIST_CATEGORY_SUCCEED: 'GET_LIST_CATEGORY_SUCCEED',
  GET_LIST_CATEGORY_FAILED: 'GET_LIST_CATEGORY_FAILED',

  GET_RECOMMEND_PRODUCT: 'GET_RECOMMEND_PRODUCT',
  GET_RECOMMEND_PRODUCT_SUCCEED: 'GET_RECOMMEND_PRODUCT_SUCCEED',
  GET_RECOMMEND_PRODUCT_FAILED: 'GET_RECOMMEND_PRODUCT_FAILED',

  SEND_VIEWED_PRODUCT: 'SEND_VIEWED_PRODUCT',
  SEND_VIEWED_PRODUCT: 'SEND_VIEWED_PRODUCT_SUCCEED',
  SEND_VIEWED_PRODUCT: 'SEND_VIEWED_PRODUCT_FAILED',

  LOGIN: 'LOGIN',
  LOGIN_SUCCEED: 'LOGIN_SUCCEED',
  LOGIN_FAILED: 'LOGIN_FAILED',

  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
  SIGNUP_FAILED: 'SIGNUP_FAILED',

  ADD_PRODUCT_CART: 'ADD_PRODUCT_CART',
  REMOVE_ALL_PRODUCT_CART: 'REMOVE_ALL_PRODUCT_CART',
  REMOVE_PRODUCT_CART: 'REMOVE_PRODUCT_CART',

  PLACE_ORDER: 'PLACE_ORDER',
  PLACE_ORDER_SUCCEED: 'PLACE_ORDER_SUCCEED',
  PLACE_ORDER_FAILED: 'PLACE_ORDER_FAILED',

  LOGOUT: 'LOGOUT'
}

export default CONSTANTS;