const CONSTANTS = {

  GET_DEAL: 'GET_DEAL',
  GET_DEAL_SUCCEED: 'GET_DEAL_SUCCEED',
  GET_DEAL_FAILD: 'GET_DEAL_FAILED',

  GET_LIST_CATEGORY_LVL1: 'GET_LIST_CATEGORY_LVL1',
  GET_LIST_CATEGORY_LVL1_SUCCEED: 'GET_LIST_CATEGORY_LVL1_SUCCEED',
  GET_LIST_CATEGORY_LVL1_FAILED: 'GET_LIST_CATEGORY_LVL1_FAILED',

  GET_LIST_CATEGORY_LVL2: 'GET_LIST_CATEGORY_LVL2',
  GET_LIST_CATEGORY_LVL2_SUCCEED: 'GET_LIST_CATEGORY_LVL2_SUCCEED',
  GET_LIST_CATEGORY_LVL2_FAILED: 'GET_LIST_CATEGORY_LVL2_FAILED',

  GET_LIST_CATEGORY_LVL2_BY_CATEGORY_LVL1: 'GET_LIST_CATEGORY_LVL2_BY_CATEGORY_LVL1',
  GET_LIST_CATEGORY_LVL2_BY_CATEGORY_LVL1_SUCCEED: 'GET_LIST_CATEGORY_LVL2_BY_CATEGORY_LVL1_SUCCEED',
  GET_LIST_CATEGORY_LVL2_BY_CATEGORY_LVL1_FAILED: 'GET_LIST_CATEGORY_LVL2_BY_CATEGORY_LVL1_FAILED',

  GET_LIST_CATEGORY_LVL3: 'GET_LIST_CATEGORY_LVL3',
  GET_LIST_CATEGORY_LVL3_SUCCEED: 'GET_LIST_CATEGORY_LVL3_SUCCEED',
  GET_LIST_CATEGORY_LVL3_FAILED: 'GET_LIST_CATEGORY_LVL3_FAILED',

  GET_LIST_CATEGORY_LVL3_BY_CATEGORY_LVL2: 'GET_LIST_CATEGORY_LVL3_BY_CATEGORY_LVL2',
  GET_LIST_CATEGORY_LVL3_BY_CATEGORY_LVL2_SUCCEED: 'GET_LIST_CATEGORY_LVL3_BY_CATEGORY_LVL2_SUCCEED',
  GET_LIST_CATEGORY_LVL3_BY_CATEGORY_LVL2_FAILED: 'GET_LIST_CATEGORY_LVL3_BY_CATEGORY_LVL2_FAILED',

  GET_TOP_PRODUCT_CATE_LVL1: 'GET_TOP_PRODUCT_CATE_LVL1',
  GET_TOP_PRODUCT_CATE_LVL1_SUCCEED: 'GET_TOP_PRODUCT_CATE_LVL1_SUCCEED',
  GET_TOP_PRODUCT_CATE_LVL1_FAILED: 'GET_TOP_PRODUCT_CATE_LVL1_FAILED',

  GET_TOP_PRODUCT_CATE_LVL2: 'GET_TOP_PRODUCT_CATE_LVL2',
  GET_TOP_PRODUCT_CATE_LVL2_SUCCEED: 'GET_TOP_PRODUCT_CATE_LVL2_SUCCEED',
  GET_TOP_PRODUCT_CATE_LVL2_FAILED: 'GET_TOP_PRODUCT_CATE_LVL2_FAILED',

  GET_TOP_PRODUCT_CATE_LVL3: 'GET_TOP_PRODUCT_CATE_LVL3',
  GET_TOP_PRODUCT_CATE_LVL3_SUCCEED: 'GET_TOP_PRODUCT_CATE_LVL3_SUCCEED',
  GET_TOP_PRODUCT_CATE_LVL3_FAILED: 'GET_TOP_PRODUCT_CATE_LVL3_FAILED',

  GET_RECOMMEND_PRODUCT: 'GET_RECOMMEND_PRODUCT',
  GET_RECOMMEND_PRODUCT_SUCCEED: 'GET_RECOMMEND_PRODUCT_SUCCEED',
  GET_RECOMMEND_PRODUCT_FAILED: 'GET_RECOMMEND_PRODUCT_FAILED',

  SAVE_VIEWED_PRODUCT: 'SAVE_VIEWED_PRODUCT',
  SEND_VIEWED_PRODUCT: 'SEND_VIEWED_PRODUCT',
  SEND_VIEWED_PRODUCT: 'SEND_VIEWED_PRODUCT_SUCCEED',
  SEND_VIEWED_PRODUCT: 'SEND_VIEWED_PRODUCT_FAILED',

  LOGIN: 'LOGIN',
  LOGIN_SUCCEED: 'LOGIN_SUCCEED',
  LOGIN_FAILED: 'LOGIN_FAILED',

  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
  SIGNUP_FAILED: 'SIGNUP_FAILED',

  ADD_PRODUCT_CART: 'ADD_PRODUCT_CART',
  ADD_EXIST_PRODUCT_CART: 'ADD_EXIST_PRODUCT_CART',
  REMOVE_ALL_PRODUCT_CART: 'REMOVE_ALL_PRODUCT_CART',
  REMOVE_PRODUCT_CART: 'REMOVE_PRODUCT_CART',
  UPDATE_CART_QUANTITY: 'UPDATE_CART_QUANTITY',
  UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
  CLEAR_CART: 'CLEAR_CART',

  PLACE_ORDER: 'PLACE_ORDER',
  PLACE_ORDER_SUCCEED: 'PLACE_ORDER_SUCCEED',
  PLACE_ORDER_FAILED: 'PLACE_ORDER_FAILED',

  SEARCH: 'SEARCH',
  SEARCH_SUCCEED: 'SEARCH_SUCCEED',
  SEARCH_FAILED: 'SEARCH_FAILED',

  LOGOUT: 'LOGOUT'
}

export default CONSTANTS;